// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$102 {

    static final FunctionDescriptor NewtonMeshGetEdgeIndices$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshGetEdgeIndices$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshGetEdgeIndices",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$102.NewtonMeshGetEdgeIndices$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshGetFirstFace$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshGetFirstFace$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshGetFirstFace",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$102.NewtonMeshGetFirstFace$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshGetNextFace$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshGetNextFace$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshGetNextFace",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$102.NewtonMeshGetNextFace$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshIsFaceOpen$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshIsFaceOpen$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshIsFaceOpen",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$102.NewtonMeshIsFaceOpen$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshGetFaceMaterial$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshGetFaceMaterial$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshGetFaceMaterial",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$102.NewtonMeshGetFaceMaterial$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshGetFaceIndexCount$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshGetFaceIndexCount$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshGetFaceIndexCount",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$102.NewtonMeshGetFaceIndexCount$FUNC, false
    );
}


