// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$46 {

    static final FunctionDescriptor NewtonFracturedCompoundCollisionGetVertexNormals$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonFracturedCompoundCollisionGetVertexNormals$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonFracturedCompoundCollisionGetVertexNormals",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$46.NewtonFracturedCompoundCollisionGetVertexNormals$FUNC, false
    );
    static final FunctionDescriptor NewtonFracturedCompoundCollisionGetVertexUVs$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonFracturedCompoundCollisionGetVertexUVs$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonFracturedCompoundCollisionGetVertexUVs",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$46.NewtonFracturedCompoundCollisionGetVertexUVs$FUNC, false
    );
    static final FunctionDescriptor NewtonFracturedCompoundMeshPartGetIndexStream$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonFracturedCompoundMeshPartGetIndexStream$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonFracturedCompoundMeshPartGetIndexStream",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$46.NewtonFracturedCompoundMeshPartGetIndexStream$FUNC, false
    );
    static final FunctionDescriptor NewtonFracturedCompoundMeshPartGetFirstSegment$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonFracturedCompoundMeshPartGetFirstSegment$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonFracturedCompoundMeshPartGetFirstSegment",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$46.NewtonFracturedCompoundMeshPartGetFirstSegment$FUNC, false
    );
    static final FunctionDescriptor NewtonFracturedCompoundMeshPartGetNextSegment$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonFracturedCompoundMeshPartGetNextSegment$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonFracturedCompoundMeshPartGetNextSegment",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$46.NewtonFracturedCompoundMeshPartGetNextSegment$FUNC, false
    );
    static final FunctionDescriptor NewtonFracturedCompoundMeshPartGetMaterial$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonFracturedCompoundMeshPartGetMaterial$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonFracturedCompoundMeshPartGetMaterial",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$46.NewtonFracturedCompoundMeshPartGetMaterial$FUNC, false
    );
}


