// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$84 {

    static final FunctionDescriptor NewtonUserJointAddLinearRow$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonUserJointAddLinearRow$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointAddLinearRow",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$84.NewtonUserJointAddLinearRow$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointAddAngularRow$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT,
        C_POINTER
    );
    static final MethodHandle NewtonUserJointAddAngularRow$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointAddAngularRow",
        "(Ljdk/incubator/foreign/MemoryAddress;FLjdk/incubator/foreign/MemoryAddress;)V",
        constants$84.NewtonUserJointAddAngularRow$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointAddGeneralRow$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonUserJointAddGeneralRow$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointAddGeneralRow",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$84.NewtonUserJointAddGeneralRow$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointSetRowMinimumFriction$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT
    );
    static final MethodHandle NewtonUserJointSetRowMinimumFriction$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointSetRowMinimumFriction",
        "(Ljdk/incubator/foreign/MemoryAddress;F)V",
        constants$84.NewtonUserJointSetRowMinimumFriction$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointSetRowMaximumFriction$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT
    );
    static final MethodHandle NewtonUserJointSetRowMaximumFriction$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointSetRowMaximumFriction",
        "(Ljdk/incubator/foreign/MemoryAddress;F)V",
        constants$84.NewtonUserJointSetRowMaximumFriction$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointCalculateRowZeroAcceleration$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER
    );
    static final MethodHandle NewtonUserJointCalculateRowZeroAcceleration$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointCalculateRowZeroAcceleration",
        "(Ljdk/incubator/foreign/MemoryAddress;)F",
        constants$84.NewtonUserJointCalculateRowZeroAcceleration$FUNC, false
    );
}


