// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$34 {

    static final FunctionDescriptor NewtonMaterialSetDefaultFriction$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle NewtonMaterialSetDefaultFriction$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMaterialSetDefaultFriction",
        "(Ljdk/incubator/foreign/MemoryAddress;IIFF)V",
        constants$34.NewtonMaterialSetDefaultFriction$FUNC, false
    );
    static final FunctionDescriptor NewtonMaterialJointResetIntraJointCollision$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle NewtonMaterialJointResetIntraJointCollision$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMaterialJointResetIntraJointCollision",
        "(Ljdk/incubator/foreign/MemoryAddress;II)V",
        constants$34.NewtonMaterialJointResetIntraJointCollision$FUNC, false
    );
    static final FunctionDescriptor NewtonMaterialJointResetSelftJointCollision$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle NewtonMaterialJointResetSelftJointCollision$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMaterialJointResetSelftJointCollision",
        "(Ljdk/incubator/foreign/MemoryAddress;II)V",
        constants$34.NewtonMaterialJointResetSelftJointCollision$FUNC, false
    );
    static final FunctionDescriptor NewtonWorldGetFirstMaterial$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonWorldGetFirstMaterial$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonWorldGetFirstMaterial",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$34.NewtonWorldGetFirstMaterial$FUNC, false
    );
    static final FunctionDescriptor NewtonWorldGetNextMaterial$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonWorldGetNextMaterial$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonWorldGetNextMaterial",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$34.NewtonWorldGetNextMaterial$FUNC, false
    );
    static final FunctionDescriptor NewtonWorldGetFirstBody$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonWorldGetFirstBody$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonWorldGetFirstBody",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$34.NewtonWorldGetFirstBody$FUNC, false
    );
}


