// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$87 {

    static final FunctionDescriptor NewtonMeshCreateTetrahedraIsoSurface$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshCreateTetrahedraIsoSurface$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshCreateTetrahedraIsoSurface",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$87.NewtonMeshCreateTetrahedraIsoSurface$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshCreateConvexHull$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT,
        C_FLOAT
    );
    static final MethodHandle NewtonMeshCreateConvexHull$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshCreateConvexHull",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;IF)Ljdk/incubator/foreign/MemoryAddress;",
        constants$87.NewtonMeshCreateConvexHull$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshCreateVoronoiConvexDecomposition$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonMeshCreateVoronoiConvexDecomposition$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshCreateVoronoiConvexDecomposition",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;IILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$87.NewtonMeshCreateVoronoiConvexDecomposition$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshCreateFromSerialization$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshCreateFromSerialization$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshCreateFromSerialization",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$87.NewtonMeshCreateFromSerialization$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshDestroy$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonMeshDestroy$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshDestroy",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$87.NewtonMeshDestroy$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshSerialize$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshSerialize$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshSerialize",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$87.NewtonMeshSerialize$FUNC, false
    );
}


