// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$35 {

    static final FunctionDescriptor NewtonWorldGetNextBody$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonWorldGetNextBody$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonWorldGetNextBody",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$35.NewtonWorldGetNextBody$FUNC, false
    );
    static final FunctionDescriptor NewtonMaterialGetMaterialPairUserData$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMaterialGetMaterialPairUserData$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMaterialGetMaterialPairUserData",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$35.NewtonMaterialGetMaterialPairUserData$FUNC, false
    );
    static final FunctionDescriptor NewtonMaterialGetContactFaceAttribute$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonMaterialGetContactFaceAttribute$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMaterialGetContactFaceAttribute",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$35.NewtonMaterialGetContactFaceAttribute$FUNC, false
    );
    static final FunctionDescriptor NewtonMaterialGetBodyCollidingShape$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMaterialGetBodyCollidingShape$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMaterialGetBodyCollidingShape",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$35.NewtonMaterialGetBodyCollidingShape$FUNC, false
    );
    static final FunctionDescriptor NewtonMaterialGetContactNormalSpeed$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER
    );
    static final MethodHandle NewtonMaterialGetContactNormalSpeed$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMaterialGetContactNormalSpeed",
        "(Ljdk/incubator/foreign/MemoryAddress;)F",
        constants$35.NewtonMaterialGetContactNormalSpeed$FUNC, false
    );
    static final FunctionDescriptor NewtonMaterialGetContactForce$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMaterialGetContactForce$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMaterialGetContactForce",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$35.NewtonMaterialGetContactForce$FUNC, false
    );
}


