// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$85 {

    static final FunctionDescriptor NewtonUserJointGetRowAcceleration$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER
    );
    static final MethodHandle NewtonUserJointGetRowAcceleration$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointGetRowAcceleration",
        "(Ljdk/incubator/foreign/MemoryAddress;)F",
        constants$85.NewtonUserJointGetRowAcceleration$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointGetRowJacobian$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonUserJointGetRowJacobian$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointGetRowJacobian",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$85.NewtonUserJointGetRowJacobian$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointSetRowAcceleration$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT
    );
    static final MethodHandle NewtonUserJointSetRowAcceleration$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointSetRowAcceleration",
        "(Ljdk/incubator/foreign/MemoryAddress;F)V",
        constants$85.NewtonUserJointSetRowAcceleration$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointSetRowMassDependentSpringDamperAcceleration$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle NewtonUserJointSetRowMassDependentSpringDamperAcceleration$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointSetRowMassDependentSpringDamperAcceleration",
        "(Ljdk/incubator/foreign/MemoryAddress;FF)V",
        constants$85.NewtonUserJointSetRowMassDependentSpringDamperAcceleration$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointSetRowMassIndependentSpringDamperAcceleration$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle NewtonUserJointSetRowMassIndependentSpringDamperAcceleration$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointSetRowMassIndependentSpringDamperAcceleration",
        "(Ljdk/incubator/foreign/MemoryAddress;FFF)V",
        constants$85.NewtonUserJointSetRowMassIndependentSpringDamperAcceleration$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointSetRowStiffness$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT
    );
    static final MethodHandle NewtonUserJointSetRowStiffness$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointSetRowStiffness",
        "(Ljdk/incubator/foreign/MemoryAddress;F)V",
        constants$85.NewtonUserJointSetRowStiffness$FUNC, false
    );
}


