// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$86 {

    static final FunctionDescriptor NewtonUserJoinRowsCount$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonUserJoinRowsCount$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJoinRowsCount",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$86.NewtonUserJoinRowsCount$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointGetGeneralRow$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonUserJointGetGeneralRow$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointGetGeneralRow",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$86.NewtonUserJointGetGeneralRow$FUNC, false
    );
    static final FunctionDescriptor NewtonUserJointGetRowForce$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle NewtonUserJointGetRowForce$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUserJointGetRowForce",
        "(Ljdk/incubator/foreign/MemoryAddress;I)F",
        constants$86.NewtonUserJointGetRowForce$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshCreate$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshCreate$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshCreate",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$86.NewtonMeshCreate$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshCreateFromMesh$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshCreateFromMesh$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshCreateFromMesh",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$86.NewtonMeshCreateFromMesh$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshCreateFromCollision$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshCreateFromCollision$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshCreateFromCollision",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$86.NewtonMeshCreateFromCollision$FUNC, false
    );
}


