// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$65 {

    static final FunctionDescriptor NewtonBodyGetDestructorCallback$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBodyGetDestructorCallback$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodyGetDestructorCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$65.NewtonBodyGetDestructorCallback$FUNC, false
    );
    static final FunctionDescriptor NewtonBodySetTransformCallback$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBodySetTransformCallback$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodySetTransformCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$65.NewtonBodySetTransformCallback$FUNC, false
    );
    static final FunctionDescriptor NewtonBodyGetTransformCallback$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBodyGetTransformCallback$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodyGetTransformCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$65.NewtonBodyGetTransformCallback$FUNC, false
    );
    static final FunctionDescriptor NewtonBodySetForceAndTorqueCallback$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBodySetForceAndTorqueCallback$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodySetForceAndTorqueCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$65.NewtonBodySetForceAndTorqueCallback$FUNC, false
    );
    static final FunctionDescriptor NewtonBodyGetForceAndTorqueCallback$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBodyGetForceAndTorqueCallback$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodyGetForceAndTorqueCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$65.NewtonBodyGetForceAndTorqueCallback$FUNC, false
    );
    static final FunctionDescriptor NewtonBodyGetID$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonBodyGetID$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodyGetID",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$65.NewtonBodyGetID$FUNC, false
    );
}


