// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$92 {

    static final FunctionDescriptor NewtonMeshSimplify$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshSimplify$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshSimplify",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$92.NewtonMeshSimplify$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshApproximateConvexDecomposition$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_FLOAT,
        C_FLOAT,
        C_INT,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshApproximateConvexDecomposition$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshApproximateConvexDecomposition",
        "(Ljdk/incubator/foreign/MemoryAddress;FFIILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$92.NewtonMeshApproximateConvexDecomposition$FUNC, false
    );
    static final FunctionDescriptor NewtonRemoveUnusedVertices$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonRemoveUnusedVertices$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonRemoveUnusedVertices",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$92.NewtonRemoveUnusedVertices$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshBeginBuild$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonMeshBeginBuild$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshBeginBuild",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$92.NewtonMeshBeginBuild$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshBeginFace$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonMeshBeginFace$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshBeginFace",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$92.NewtonMeshBeginFace$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshAddPoint$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle NewtonMeshAddPoint$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshAddPoint",
        "(Ljdk/incubator/foreign/MemoryAddress;DDD)V",
        constants$92.NewtonMeshAddPoint$FUNC, false
    );
}


