// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$54 {

    static final FunctionDescriptor NewtonCollisionGetParentInstance$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonCollisionGetParentInstance$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonCollisionGetParentInstance",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$54.NewtonCollisionGetParentInstance$FUNC, false
    );
    static final FunctionDescriptor NewtonCollisionSetMatrix$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonCollisionSetMatrix$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonCollisionSetMatrix",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$54.NewtonCollisionSetMatrix$FUNC, false
    );
    static final FunctionDescriptor NewtonCollisionGetMatrix$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonCollisionGetMatrix$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonCollisionGetMatrix",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$54.NewtonCollisionGetMatrix$FUNC, false
    );
    static final FunctionDescriptor NewtonCollisionSetScale$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle NewtonCollisionSetScale$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonCollisionSetScale",
        "(Ljdk/incubator/foreign/MemoryAddress;FFF)V",
        constants$54.NewtonCollisionSetScale$FUNC, false
    );
    static final FunctionDescriptor NewtonCollisionGetScale$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonCollisionGetScale$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonCollisionGetScale",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$54.NewtonCollisionGetScale$FUNC, false
    );
    static final FunctionDescriptor NewtonDestroyCollision$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonDestroyCollision$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonDestroyCollision",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$54.NewtonDestroyCollision$FUNC, false
    );
}


