// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$81 {

    static final FunctionDescriptor NewtonCorkscrewCalculateStopAccel$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER,
        C_POINTER,
        C_FLOAT
    );
    static final MethodHandle NewtonCorkscrewCalculateStopAccel$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonCorkscrewCalculateStopAccel",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;F)F",
        constants$81.NewtonCorkscrewCalculateStopAccel$FUNC, false
    );
    static final FunctionDescriptor NewtonConstraintCreateUniversal$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonConstraintCreateUniversal$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonConstraintCreateUniversal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$81.NewtonConstraintCreateUniversal$FUNC, false
    );
    static final FunctionDescriptor NewtonUniversalSetUserCallback$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonUniversalSetUserCallback$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUniversalSetUserCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$81.NewtonUniversalSetUserCallback$FUNC, false
    );
    static final FunctionDescriptor NewtonUniversalGetJointAngle0$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER
    );
    static final MethodHandle NewtonUniversalGetJointAngle0$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUniversalGetJointAngle0",
        "(Ljdk/incubator/foreign/MemoryAddress;)F",
        constants$81.NewtonUniversalGetJointAngle0$FUNC, false
    );
    static final FunctionDescriptor NewtonUniversalGetJointAngle1$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER
    );
    static final MethodHandle NewtonUniversalGetJointAngle1$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUniversalGetJointAngle1",
        "(Ljdk/incubator/foreign/MemoryAddress;)F",
        constants$81.NewtonUniversalGetJointAngle1$FUNC, false
    );
    static final FunctionDescriptor NewtonUniversalGetJointOmega0$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER
    );
    static final MethodHandle NewtonUniversalGetJointOmega0$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonUniversalGetJointOmega0",
        "(Ljdk/incubator/foreign/MemoryAddress;)F",
        constants$81.NewtonUniversalGetJointOmega0$FUNC, false
    );
}


