// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$76 {

    static final FunctionDescriptor NewtonCreateDeformableSolid$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle NewtonCreateDeformableSolid$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonCreateDeformableSolid",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
        constants$76.NewtonCreateDeformableSolid$FUNC, false
    );
    static final FunctionDescriptor NewtonDeformableMeshGetParticleCount$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonDeformableMeshGetParticleCount$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonDeformableMeshGetParticleCount",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$76.NewtonDeformableMeshGetParticleCount$FUNC, false
    );
    static final FunctionDescriptor NewtonDeformableMeshGetParticleStrideInBytes$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonDeformableMeshGetParticleStrideInBytes$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonDeformableMeshGetParticleStrideInBytes",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$76.NewtonDeformableMeshGetParticleStrideInBytes$FUNC, false
    );
    static final FunctionDescriptor NewtonDeformableMeshGetParticleArray$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonDeformableMeshGetParticleArray$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonDeformableMeshGetParticleArray",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$76.NewtonDeformableMeshGetParticleArray$FUNC, false
    );
    static final FunctionDescriptor NewtonConstraintCreateBall$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonConstraintCreateBall$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonConstraintCreateBall",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$76.NewtonConstraintCreateBall$FUNC, false
    );
    static final FunctionDescriptor NewtonBallSetUserCallback$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBallSetUserCallback$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBallSetUserCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$76.NewtonBallSetUserCallback$FUNC, false
    );
}


