// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$15 {

    static final FunctionDescriptor NewtonCollisionIterator$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle NewtonCollisionIterator$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)V",
        constants$15.NewtonCollisionIterator$FUNC, false
    );
    static final FunctionDescriptor NewtonBallCallback$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT
    );
    static final MethodHandle NewtonBallCallback$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;F)V",
        constants$15.NewtonBallCallback$FUNC, false
    );
    static final FunctionDescriptor NewtonHingeCallback$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonHingeCallback$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$15.NewtonHingeCallback$FUNC, false
    );
}


