// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$66 {

    static final FunctionDescriptor NewtonBodySetUserData$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBodySetUserData$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodySetUserData",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$66.NewtonBodySetUserData$FUNC, false
    );
    static final FunctionDescriptor NewtonBodyGetUserData$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBodyGetUserData$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodyGetUserData",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$66.NewtonBodyGetUserData$FUNC, false
    );
    static final FunctionDescriptor NewtonBodyGetWorld$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBodyGetWorld$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodyGetWorld",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$66.NewtonBodyGetWorld$FUNC, false
    );
    static final FunctionDescriptor NewtonBodyGetCollision$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonBodyGetCollision$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodyGetCollision",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$66.NewtonBodyGetCollision$FUNC, false
    );
    static final FunctionDescriptor NewtonBodyGetMaterialGroupID$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonBodyGetMaterialGroupID$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodyGetMaterialGroupID",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$66.NewtonBodyGetMaterialGroupID$FUNC, false
    );
    static final FunctionDescriptor NewtonBodyGetSerializedID$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonBodyGetSerializedID$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonBodyGetSerializedID",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$66.NewtonBodyGetSerializedID$FUNC, false
    );
}


