// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$90 {

    static final FunctionDescriptor NewtonMeshOptimize$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonMeshOptimize$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshOptimize",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$90.NewtonMeshOptimize$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshOptimizePoints$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonMeshOptimizePoints$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshOptimizePoints",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$90.NewtonMeshOptimizePoints$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshOptimizeVertex$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonMeshOptimizeVertex$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshOptimizeVertex",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$90.NewtonMeshOptimizeVertex$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshIsOpenMesh$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonMeshIsOpenMesh$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshIsOpenMesh",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$90.NewtonMeshIsOpenMesh$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshFixTJoints$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonMeshFixTJoints$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshFixTJoints",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$90.NewtonMeshFixTJoints$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshPolygonize$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonMeshPolygonize$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshPolygonize",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$90.NewtonMeshPolygonize$FUNC, false
    );
}


