// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$74 {

    static final FunctionDescriptor NewtonJointSetUserData$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonJointSetUserData$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonJointSetUserData",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$74.NewtonJointSetUserData$FUNC, false
    );
    static final FunctionDescriptor NewtonJointGetBody0$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonJointGetBody0$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonJointGetBody0",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$74.NewtonJointGetBody0$FUNC, false
    );
    static final FunctionDescriptor NewtonJointGetBody1$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonJointGetBody1$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonJointGetBody1",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$74.NewtonJointGetBody1$FUNC, false
    );
    static final FunctionDescriptor NewtonJointGetInfo$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonJointGetInfo$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonJointGetInfo",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$74.NewtonJointGetInfo$FUNC, false
    );
    static final FunctionDescriptor NewtonJointGetCollisionState$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle NewtonJointGetCollisionState$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonJointGetCollisionState",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$74.NewtonJointGetCollisionState$FUNC, false
    );
    static final FunctionDescriptor NewtonJointSetCollisionState$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT
    );
    static final MethodHandle NewtonJointSetCollisionState$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonJointSetCollisionState",
        "(Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$74.NewtonJointSetCollisionState$FUNC, false
    );
}


