// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$103 {

    static final FunctionDescriptor NewtonMeshGetFaceIndices$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshGetFaceIndices$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshGetFaceIndices",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$103.NewtonMeshGetFaceIndices$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshGetFacePointIndices$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshGetFacePointIndices$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshGetFacePointIndices",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$103.NewtonMeshGetFacePointIndices$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshCalculateFaceNormal$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshCalculateFaceNormal$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshCalculateFaceNormal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$103.NewtonMeshCalculateFaceNormal$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshSetFaceMaterial$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle NewtonMeshSetFaceMaterial$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshSetFaceMaterial",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$103.NewtonMeshSetFaceMaterial$FUNC, false
    );
}


