// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1 {

    static final FunctionDescriptor NewtonPostUpdateCallback$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT
    );
    static final MethodHandle NewtonPostUpdateCallback$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;F)V",
        constants$1.NewtonPostUpdateCallback$FUNC, false
    );
    static final FunctionDescriptor NewtonCreateContactCallback$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonCreateContactCallback$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1.NewtonCreateContactCallback$FUNC, false
    );
    static final FunctionDescriptor NewtonDestroyContactCallback$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonDestroyContactCallback$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1.NewtonDestroyContactCallback$FUNC, false
    );
}


