// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$88 {

    static final FunctionDescriptor NewtonMeshSaveOFF$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshSaveOFF$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshSaveOFF",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$88.NewtonMeshSaveOFF$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshLoadOFF$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshLoadOFF$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshLoadOFF",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$88.NewtonMeshLoadOFF$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshLoadTetrahedraMesh$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshLoadTetrahedraMesh$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshLoadTetrahedraMesh",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$88.NewtonMeshLoadTetrahedraMesh$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshFlipWinding$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle NewtonMeshFlipWinding$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshFlipWinding",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$88.NewtonMeshFlipWinding$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshApplyTransform$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshApplyTransform$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshApplyTransform",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$88.NewtonMeshApplyTransform$FUNC, false
    );
    static final FunctionDescriptor NewtonMeshCalculateOOBB$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NewtonMeshCalculateOOBB$MH = RuntimeHelper.downcallHandle(
        Newton_h.LIBRARIES, "NewtonMeshCalculateOOBB",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$88.NewtonMeshCalculateOOBB$FUNC, false
    );
}


