// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface NewtonReportProgress {

    int apply(float x0, jdk.incubator.foreign.MemoryAddress x1);
    static MemoryAddress allocate(NewtonReportProgress fi) {
        return RuntimeHelper.upcallStub(NewtonReportProgress.class, fi, constants$18.NewtonReportProgress$FUNC, "(FLjdk/incubator/foreign/MemoryAddress;)I");
    }
    static MemoryAddress allocate(NewtonReportProgress fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(NewtonReportProgress.class, fi, constants$18.NewtonReportProgress$FUNC, "(FLjdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static NewtonReportProgress ofAddress(MemoryAddress addr) {
        return (float x0, jdk.incubator.foreign.MemoryAddress x1) -> {
            try {
                return (int)constants$18.NewtonReportProgress$MH.invokeExact((Addressable)addr, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


