// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface NewtonUserMeshCollisionGetCollisionInfo {

    void apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1);
    static MemoryAddress allocate(NewtonUserMeshCollisionGetCollisionInfo fi) {
        return RuntimeHelper.upcallStub(NewtonUserMeshCollisionGetCollisionInfo.class, fi, constants$6.NewtonUserMeshCollisionGetCollisionInfo$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V");
    }
    static MemoryAddress allocate(NewtonUserMeshCollisionGetCollisionInfo fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(NewtonUserMeshCollisionGetCollisionInfo.class, fi, constants$6.NewtonUserMeshCollisionGetCollisionInfo$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static NewtonUserMeshCollisionGetCollisionInfo ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1) -> {
            try {
                constants$6.NewtonUserMeshCollisionGetCollisionInfo$MH.invokeExact((Addressable)addr, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


