// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface NewtonCollisionTreeRayCastCallback {

    float apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, float x2, jdk.incubator.foreign.MemoryAddress x3, int x4, jdk.incubator.foreign.MemoryAddress x5);
    static MemoryAddress allocate(NewtonCollisionTreeRayCastCallback fi) {
        return RuntimeHelper.upcallStub(NewtonCollisionTreeRayCastCallback.class, fi, constants$8.NewtonCollisionTreeRayCastCallback$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;FLjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)F");
    }
    static MemoryAddress allocate(NewtonCollisionTreeRayCastCallback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(NewtonCollisionTreeRayCastCallback.class, fi, constants$8.NewtonCollisionTreeRayCastCallback$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;FLjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)F", scope);
    }
    static NewtonCollisionTreeRayCastCallback ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, float x2, jdk.incubator.foreign.MemoryAddress x3, int x4, jdk.incubator.foreign.MemoryAddress x5) -> {
            try {
                return (float)constants$8.NewtonCollisionTreeRayCastCallback$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4, x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


