// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface NewtonApplyForceAndTorque {

    void apply(jdk.incubator.foreign.MemoryAddress x0, float x1, int x2);
    static MemoryAddress allocate(NewtonApplyForceAndTorque fi) {
        return RuntimeHelper.upcallStub(NewtonApplyForceAndTorque.class, fi, constants$10.NewtonApplyForceAndTorque$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;FI)V");
    }
    static MemoryAddress allocate(NewtonApplyForceAndTorque fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(NewtonApplyForceAndTorque.class, fi, constants$10.NewtonApplyForceAndTorque$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;FI)V", scope);
    }
    static NewtonApplyForceAndTorque ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0, float x1, int x2) -> {
            try {
                constants$10.NewtonApplyForceAndTorque$MH.invokeExact((Addressable)addr, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


