// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface NewtonWorldUpdateListenerCallback {

    void apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, float x2);
    static MemoryAddress allocate(NewtonWorldUpdateListenerCallback fi) {
        return RuntimeHelper.upcallStub(NewtonWorldUpdateListenerCallback.class, fi, constants$2.NewtonWorldUpdateListenerCallback$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;F)V");
    }
    static MemoryAddress allocate(NewtonWorldUpdateListenerCallback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(NewtonWorldUpdateListenerCallback.class, fi, constants$2.NewtonWorldUpdateListenerCallback$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;F)V", scope);
    }
    static NewtonWorldUpdateListenerCallback ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, float x2) -> {
            try {
                constants$2.NewtonWorldUpdateListenerCallback$MH.invokeExact((Addressable)addr, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


