// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class NewtonCollisionInfoRecord {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(4, MemoryLayout.sequenceLayout(4, C_FLOAT)).withName("m_offsetMatrix"),
        MemoryLayout.structLayout(
            C_LONG_LONG.withName("m_userId"),
            MemoryLayout.unionLayout(
                C_POINTER.withName("m_ptr"),
                C_LONG_LONG.withName("m_int"),
                C_FLOAT.withName("m_float")
            ).withName("m_userData"),
            MemoryLayout.sequenceLayout(6, MemoryLayout.unionLayout(
                C_POINTER.withName("m_ptr"),
                C_LONG_LONG.withName("m_int"),
                C_FLOAT.withName("m_float")
            )).withName("m_userParam")
        ).withName("m_collisionMaterial"),
        C_INT.withName("m_collisionType"),
        MemoryLayout.paddingLayout(32),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                C_FLOAT.withName("m_x"),
                C_FLOAT.withName("m_y"),
                C_FLOAT.withName("m_z")
            ).withName("m_box"),
            MemoryLayout.structLayout(
                C_FLOAT.withName("m_radio"),
                C_FLOAT.withName("m_height")
            ).withName("m_cone"),
            MemoryLayout.structLayout(
                C_FLOAT.withName("m_radio")
            ).withName("m_sphere"),
            MemoryLayout.structLayout(
                C_FLOAT.withName("m_radio0"),
                C_FLOAT.withName("m_radio1"),
                C_FLOAT.withName("m_height")
            ).withName("m_capsule"),
            MemoryLayout.structLayout(
                C_FLOAT.withName("m_radio0"),
                C_FLOAT.withName("m_radio1"),
                C_FLOAT.withName("m_height")
            ).withName("m_cylinder"),
            MemoryLayout.structLayout(
                C_FLOAT.withName("m_radio"),
                C_FLOAT.withName("m_height")
            ).withName("m_chamferCylinder"),
            MemoryLayout.structLayout(
                C_INT.withName("m_vertexCount"),
                C_INT.withName("m_vertexStrideInBytes"),
                C_INT.withName("m_faceCount"),
                MemoryLayout.paddingLayout(32),
                C_POINTER.withName("m_vertex")
            ).withName("m_convexHull"),
            MemoryLayout.structLayout(
                C_INT.withName("m_vertexCount"),
                C_INT.withName("m_triangleCount"),
                C_INT.withName("m_vrtexStrideInBytes"),
                MemoryLayout.paddingLayout(32),
                C_POINTER.withName("m_indexList"),
                C_POINTER.withName("m_vertexList")
            ).withName("m_deformableMesh"),
            MemoryLayout.structLayout(
                C_INT.withName("m_chidrenCount")
            ).withName("m_compoundCollision"),
            MemoryLayout.structLayout(
                C_INT.withName("m_vertexCount"),
                C_INT.withName("m_indexCount")
            ).withName("m_collisionTree"),
            MemoryLayout.structLayout(
                C_INT.withName("m_width"),
                C_INT.withName("m_height"),
                C_INT.withName("m_gridsDiagonals"),
                C_INT.withName("m_elevationDataType"),
                C_FLOAT.withName("m_verticalScale"),
                C_FLOAT.withName("m_horizonalScale_x"),
                C_FLOAT.withName("m_horizonalScale_z"),
                MemoryLayout.paddingLayout(32),
                C_POINTER.withName("m_vertialElevation"),
                C_POINTER.withName("m_atributes")
            ).withName("m_heightField"),
            MemoryLayout.structLayout(
                C_INT.withName("m_childrenProxyCount")
            ).withName("m_sceneCollision"),
            MemoryLayout.sequenceLayout(64, C_FLOAT).withName("m_paramArray")
        ).withName("$anon$0")
    ).withName("NewtonCollisionInfoRecord");
    public static MemoryLayout $LAYOUT() {
        return NewtonCollisionInfoRecord.$struct$LAYOUT;
    }
    public static MemorySegment m_offsetMatrix$slice(MemorySegment seg) {
        return seg.asSlice(0, 64);
    }
    public static MemorySegment m_collisionMaterial$slice(MemorySegment seg) {
        return seg.asSlice(64, 64);
    }
    static final VarHandle m_collisionType$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("m_collisionType"));
    public static VarHandle m_collisionType$VH() {
        return NewtonCollisionInfoRecord.m_collisionType$VH;
    }
    public static int m_collisionType$get(MemorySegment seg) {
        return (int)NewtonCollisionInfoRecord.m_collisionType$VH.get(seg);
    }
    public static void m_collisionType$set( MemorySegment seg, int x) {
        NewtonCollisionInfoRecord.m_collisionType$VH.set(seg, x);
    }
    public static int m_collisionType$get(MemorySegment seg, long index) {
        return (int)NewtonCollisionInfoRecord.m_collisionType$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void m_collisionType$set(MemorySegment seg, long index, int x) {
        NewtonCollisionInfoRecord.m_collisionType$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment m_box$slice(MemorySegment seg) {
        return seg.asSlice(136, 12);
    }
    public static MemorySegment m_cone$slice(MemorySegment seg) {
        return seg.asSlice(136, 8);
    }
    public static MemorySegment m_sphere$slice(MemorySegment seg) {
        return seg.asSlice(136, 4);
    }
    public static MemorySegment m_capsule$slice(MemorySegment seg) {
        return seg.asSlice(136, 12);
    }
    public static MemorySegment m_cylinder$slice(MemorySegment seg) {
        return seg.asSlice(136, 12);
    }
    public static MemorySegment m_chamferCylinder$slice(MemorySegment seg) {
        return seg.asSlice(136, 8);
    }
    public static MemorySegment m_convexHull$slice(MemorySegment seg) {
        return seg.asSlice(136, 24);
    }
    public static MemorySegment m_deformableMesh$slice(MemorySegment seg) {
        return seg.asSlice(136, 32);
    }
    public static MemorySegment m_compoundCollision$slice(MemorySegment seg) {
        return seg.asSlice(136, 4);
    }
    public static MemorySegment m_collisionTree$slice(MemorySegment seg) {
        return seg.asSlice(136, 8);
    }
    public static MemorySegment m_heightField$slice(MemorySegment seg) {
        return seg.asSlice(136, 48);
    }
    public static MemorySegment m_sceneCollision$slice(MemorySegment seg) {
        return seg.asSlice(136, 4);
    }
    public static MemorySegment m_paramArray$slice(MemorySegment seg) {
        return seg.asSlice(136, 256);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


