// Generated by jextract

package com.newton;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface NewtonConstraintDestructor {

    void apply(jdk.incubator.foreign.MemoryAddress x0);
    static MemoryAddress allocate(NewtonConstraintDestructor fi) {
        return RuntimeHelper.upcallStub(NewtonConstraintDestructor.class, fi, constants$17.NewtonConstraintDestructor$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)V");
    }
    static MemoryAddress allocate(NewtonConstraintDestructor fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(NewtonConstraintDestructor.class, fi, constants$17.NewtonConstraintDestructor$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static NewtonConstraintDestructor ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                constants$17.NewtonConstraintDestructor$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


